冲突
    组员1：
        ~~git clone remote_URL~~
    组员2：
        ~~git clone remote_URL~~
    组员1：
        对文件1进行新的工作
        ~~git add 文件1~~
        ~~git commit -m '提交说明'~~
        ~~git push origin dev~~
    组员2：
        对文件1进行新的工作（与组员1的工作不同）
        ~~git add 文件1~~
        ~~git commit -m '提交说明'~~
        ~~git push origin dev~~
        此时：
            会出现冲突，提示如下：
            ~~`
             ! [rejected]        main -> main (fetch first)
            error: 无法推送一些引用到 '远程仓库地址'
            提示：更新被拒绝，因为远程仓库包含您本地尚不存在的提交。这通常是因为另外
            提示：一个仓库已向该引用进行了推送。再次推送前，您可能需要先整合远程变更
            提示：（如 'git pull ...'）。
            提示：详见 'git push --help' 中的 'Note about fast-forwards' 小节。
            ~~`
        根据提示，需要先获取服务器的变更~~git pull~~，发现有冲突，而且自动合并冲突失败，需要手动合并冲突，此时需要与组员1沟通，然后确定代码内容，如此则冲突解决完成
        ~~git add 文件1~~
        ~~git commit -m '提交说明'~~
        ~~git push origin dev~~
